---
version: "1"
rules:
  - base: master
    upstream: Nefelim4ag:Ananicy
    mergeMethod: rebase
    assignees:
      - RogueScholar
    reviewers:
      - RogueScholar
  - base: debian
    upstream: Nefelim4ag:Ananicy
    mergeMethod: rebase
    assignees:
      - RogueScholar
    reviewers:
      - RogueScholar
label: ":arrow_heading_down: pull"
...
